from django.conf.urls import url 
from . import views 

from django.urls import path
from rest_framework.authtoken import views as rfa_views
 
urlpatterns = [
    path('api/token/', rfa_views.obtain_auth_token, name="api-token-auth"),

    url(r'^api/tutorials$', views.tutorial_list),
    url(r'^api/tutorials/(?P<pk>[0-9]+)$', views.tutorial_detail),
    url(r'^api/tutorials/published$', views.tutorial_list_published),
    
    url(r'^api/users$', views.users_list),
    url(r'^api/users/(?P<pk>[0-9]+)$', views.users_detail),
    url(r'^api/users/active$', views.users_list_active),

    url(r'^api/audits$', views.audits_list),
    url(r'^api/audits/(?P<pk>[0-9]+)$', views.audits_detail),
    url(r'^api/audits/active$', views.audits_list_active),
    url(r'^api/cooperatives$', views.cooperatives_list),
    url(r'^api/cooperatives/(?P<pk>[0-9]+)$', views.cooperatives_detail),
    url(r'^api/cooperatives/active$', views.cooperatives_list_active),
    url(r'^api/produce$', views.produce_list),
    url(r'^api/produce/(?P<pk>[0-9]+)$', views.produce_detail),
    url(r'^api/produce/active$', views.produce_list_active),
    url(r'^api/factories$', views.factories_list),
    url(r'^api/factories/(?P<pk>[0-9]+)$', views.factories_detail),
    url(r'^api/factories/active$', views.factories_list_active),

    url(r'^api/devices$', views.devices_list),
    url(r'^api/devices/(?P<pk>[0-9]+)$', views.devices_detail),
    url(r'^api/devices/active$', views.devices_list_active),

    url(r'^api/clerks$', views.clerk_list),
    url(r'^api/clerks/(?P<pk>[0-9]+)$', views.clerk_detail),
    url(r'^api/clerks/active$', views.clerk_list_active),
    url(r'^api/farmers$', views.farmers_list),
    url(r'^api/farmers/(?P<pk>[0-9]+)$', views.farmers_detail),
    url(r'^api/farmers/active$', views.farmers_list_active),
    url(r'^api/transactions$', views.transactions_list),
    url(r'^api/transactions/(?P<pk>[0-9]+)$', views.transactions_detail),
    url(r'^api/transactions/active$', views.transactions_list_active),
     url(r'^api/transactions/total/(?P<pk>[0-9]+)$', views.transactions_total),
    url(r'^api/payment$', views.payment_list),
    url(r'^api/payment/(?P<pk>[0-9]+)$', views.payment_detail),
    url(r'^api/payment/active$', views.payment_list_active),

    url(r'^api/accounts$', views.accounts_list),
    url(r'^api/accounts/(?P<pk>[0-9]+)$', views.accounts_detail),
    url(r'^api/accounts/active$', views.accounts_list_active), 
    url(r'^api/productweights$', views.productweights_list),
    url(r'^api/productweights/(?P<pk>[0-9]+)$', views.productweights_detail),
    url(r'^api/productsweights/active$', views.productweights_list_active),
    url(r'^api/sku$', views.sku_list),
    url(r'^api/sku/(?P<pk>[0-9]+)$', views.sku_detail),
    url(r'^api/sku/active$', views.sku_list_active),
    url(r'^api/products$', views.products_list),
    url(r'^api/products/(?P<pk>[0-9]+)$', views.products_detail),
    url(r'^api/products/active$', views.products_list_active),

    url(r'^api/destination$', views.destination_list),
    url(r'^api/destination/(?P<pk>[0-9]+)$', views.destination_detail),
    url(r'^api/destination/active$', views.destination_list_active),
    url(r'^api/origin$', views.origin_list),
    url(r'^api/origin/(?P<pk>[0-9]+)$', views.origin_detail),
    url(r'^api/origin/active$', views.origin_list_active),
    url(r'^api/suppliers$', views.suppliers_list),
    url(r'^api/suppliers/(?P<pk>[0-9]+)$', views.suppliers_detail),
    url(r'^api/suppliers/active$', views.suppliers_list_active),
    url(r'^api/weighbridges$', views.weighbridges_list),
    url(r'^api/weighbridges/(?P<pk>[0-9]+)$', views.weighbridges_detail),
    url(r'^api/weighbridges/active$', views.weighbridges_list_active),
    url(r'^api/customers$', views.customers_list),
    url(r'^api/customers/(?P<pk>[0-9]+)$', views.customers_detail),
    url(r'^api/customers/active$', views.customers_list_active),
    url(r'^api/transporters$', views.transporters_list),
    url(r'^api/transporters/(?P<pk>[0-9]+)$', views.transporters_detail),
    url(r'^api/transporters/active$', views.transporters_list_active), 
    url(r'^api/vehicle$', views.vehicle_list),
    url(r'^api/vehicle/(?P<pk>[0-9]+)$', views.vehicle_detail),
    url(r'^api/vehicle/active$', views.vehicle_list_active),
    url(r'^api/commodity$', views.commodity_list),
    url(r'^api/commodity/(?P<pk>[0-9]+)$', views.commodity_detail),
    url(r'^api/commodity/active$', views.commodity_list_active),
    url(r'^api/employees$', views.employees_list),
    url(r'^api/employees/(?P<pk>[0-9]+)$', views.employees_detail),
    url(r'^api/employees/active$', views.employees_list_active),
    url(r'^api/shifts$', views.shifts_list),
    url(r'^api/shifts/(?P<pk>[0-9]+)$', views.shifts_detail),
    url(r'^api/shifts/active$', views.shifts_list_active),
    url(r'^api/operators$', views.operators_list),
    url(r'^api/operators/(?P<pk>[0-9]+)$', views.operators_detail),
    url(r'^api/operators/active$', views.operators_list_active),
    url(r'^api/shiftsrecords$', views.shiftsrecords_list),
    url(r'^api/shiftsrecords/(?P<pk>[0-9]+)$', views.shiftsrecords_detail),
    url(r'^api/shiftsrecords/active$', views.shiftsrecords_list_active),
    url(r'^api/weighstages$', views.weighstages_list),
    url(r'^api/weighstages/(?P<pk>[0-9]+)$', views.weighstages_detail),
    url(r'^api/weighstages/active$', views.weighstages_list_active),
    url(r'^api/tickets$', views.tickets_list),
    url(r'^api/tickets/(?P<pk>[0-9]+)$', views.tickets_detail),
    url(r'^api/tickets/active$', views.tickets_list_active),
    url(r'^api/connectionsserial$', views.connectionsserial_list),
    url(r'^api/connectionsserial/(?P<pk>[0-9]+)$', views.connectionsserial_detail),
    url(r'^api/connectionsserial/active$', views.connectionsserial_list_active),
    url(r'^api/connectionsetho$', views.connectionsetho_list),
    url(r'^api/connectionsetho/(?P<pk>[0-9]+)$', views.connectionsetho_detail),
    url(r'^api/connectionsetho/active$', views.connectionsetho_list_active),
    url(r'^api/expirydates$', views.expirydates_list),
    url(r'^api/expirydates/(?P<pk>[0-9]+)$', views.expirydates_detail),
    url(r'^api/expirydates/active$', views.expirydates_list_active),


    url(r'^api/gdc/destination$', views.destination_list),
    url(r'^api/gdc/destination/(?P<pk>[0-9]+)$', views.destination_detail),
    url(r'^api/gdc/destination/active$', views.destination_list_active),
    url(r'^api/gdc/origin$', views.origin_list),
    url(r'^api/gdc/origin/(?P<pk>[0-9]+)$', views.origin_detail),
    url(r'^api/gdc/origin/active$', views.origin_list_active),
    url(r'^api/gdc/suppliers$', views.suppliers_list),
    url(r'^api/gdc/suppliers/(?P<pk>[0-9]+)$', views.suppliers_detail),
    url(r'^api/gdc/suppliers/active$', views.suppliers_list_active),
    url(r'^api/gdc/weighbridges$', views.weighbridges_list),
    url(r'^api/gdc/weighbridges/(?P<pk>[0-9]+)$', views.weighbridges_detail),
    url(r'^api/gdc/weighbridges/active$', views.weighbridges_list_active),
    url(r'^api/gdc/customers$', views.customers_list),
    url(r'^api/gdc/customers/(?P<pk>[0-9]+)$', views.customers_detail),
    url(r'^api/gdc/customers/active$', views.customers_list_active),
    url(r'^api/gdc/transporters$', views.transporters_list),
    url(r'^api/gdc/transporters/(?P<pk>[0-9]+)$', views.transporters_detail),
    url(r'^api/gdc/transporters/active$', views.transporters_list_active), 
    url(r'^api/gdc/vehicle$', views.vehicle_list),
    url(r'^api/gdc/vehicle/(?P<pk>[0-9]+)$', views.vehicle_detail),
    url(r'^api/gdc/vehicle/active$', views.vehicle_list_active),
    url(r'^api/gdc/commodity$', views.commodity_list),
    url(r'^api/gdc/commodity/(?P<pk>[0-9]+)$', views.commodity_detail),
    url(r'^api/gdc/commodity/active$', views.commodity_list_active),
    url(r'^api/gdc/employees$', views.employees_list),
    url(r'^api/gdc/employees/(?P<pk>[0-9]+)$', views.employees_detail),
    url(r'^api/gdc/employees/active$', views.employees_list_active),
    url(r'^api/gdc/shifts$', views.shifts_list),
    url(r'^api/gdc/shifts/(?P<pk>[0-9]+)$', views.shifts_detail),
    url(r'^api/gdc/shifts/active$', views.shifts_list_active),
    url(r'^api/gdc/operators$', views.operators_list),
    url(r'^api/gdc/operators/(?P<pk>[0-9]+)$', views.operators_detail),
    url(r'^api/gdc/operators/active$', views.operators_list_active),
    url(r'^api/gdc/shiftsrecords$', views.shiftsrecords_list),
    url(r'^api/gdc/shiftsrecords/(?P<pk>[0-9]+)$', views.shiftsrecords_detail),
    url(r'^api/gdc/shiftsrecords/active$', views.shiftsrecords_list_active),
    url(r'^api/gdc/weighstages$', views.weighstages_list),
    url(r'^api/gdc/weighstages/(?P<pk>[0-9]+)$', views.weighstages_detail),
    url(r'^api/gdc/weighstages/active$', views.weighstages_list_active),
    url(r'^api/gdc/tickets$', views.tickets_list),
    url(r'^api/gdc/tickets/(?P<pk>[0-9]+)$', views.tickets_detail),
    url(r'^api/gdc/tickets/active$', views.tickets_list_active),
    url(r'^api/gdc/connectionsserial$', views.connectionsserial_list),
    url(r'^api/gdc/connectionsserial/(?P<pk>[0-9]+)$', views.connectionsserial_detail),
    url(r'^api/gdc/connectionsserial/active$', views.connectionsserial_list_active),
    url(r'^api/gdc/connectionsetho$', views.connectionsetho_list),
    url(r'^api/gdc/connectionsetho/(?P<pk>[0-9]+)$', views.connectionsetho_detail),
    url(r'^api/gdc/connectionsetho/active$', views.connectionsetho_list_active),
    url(r'^api/gdc/expirydates$', views.expirydates_list),
    url(r'^api/gdc/expirydates/(?P<pk>[0-9]+)$', views.expirydates_detail),
    url(r'^api/gdc/expirydates/active$', views.expirydates_list_active)
]