# Generated by Django 3.1.1 on 2020-09-22 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Commodity',
            },
        ),
        migrations.CreateModel(
            name='ConnectionsEtho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=50)),
                ('mac_address', models.CharField(default=None, max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Ethernet Connections',
            },
        ),
        migrations.CreateModel(
            name='ConnectionsSerial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('baud', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Serial Connections',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('account', models.ManyToManyField(to='tutorials.Accounts')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='ExpiryDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('licence', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('reg_date', models.DateTimeField()),
                ('exp_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Expiry Dates',
            },
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.employees')),
            ],
            options={
                'verbose_name_plural': 'Operators',
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('clock_in', models.TimeField()),
                ('clock_out', models.TimeField()),
                ('status', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Shifts',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('account', models.ManyToManyField(to='tutorials.Accounts')),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Transporters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('contact', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('supplier', models.ManyToManyField(to='tutorials.Suppliers')),
            ],
            options={
                'verbose_name_plural': 'Transporters',
            },
        ),
        migrations.CreateModel(
            name='Weighbridges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('long', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Weighbridges',
            },
        ),
        migrations.CreateModel(
            name='WeighStages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stages', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Weigh Stages',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('no_plate', models.CharField(max_length=20)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.transporters')),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('first_weight', models.CharField(max_length=50)),
                ('second_weight', models.CharField(default=None, max_length=50)),
                ('pub_date_first', models.DateTimeField()),
                ('pub_date_second', models.DateTimeField()),
                ('front_photo', models.FileField(default=None, upload_to='documents/tractors/tickets/front')),
                ('side_photo', models.FileField(default=None, upload_to='documents/tractors/tickets/side')),
                ('back_photo', models.FileField(default=None, upload_to='documents/tractors/tickets/back')),
                ('plate_photo', models.FileField(default=None, upload_to='documents/tractors/tickets/plate')),
                ('operation', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=10)),
                ('commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.commodity')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.customers')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.destination')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.operators')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.origin')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.suppliers')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.vehicle')),
                ('weigh_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.weighstages')),
                ('weighbridge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.weighbridges')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='ShiftsRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.operators')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.shifts')),
            ],
            options={
                'verbose_name_plural': 'Shifts Performance',
            },
        ),
    ]
