# Generated by Django 3.1.4 on 2020-12-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='device',
            new_name='device_info',
        ),
    ]
