# Generated by Django 3.1.1 on 2020-09-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_accounts_commodity_connectionsetho_connectionsserial_customers_destination_employees_expirydates_ope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='account',
            field=models.ManyToManyField(related_name='account', to='tutorials.Accounts'),
        ),
    ]
