# Generated by Django 3.1.4 on 2020-12-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20201221_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.devices'),
        ),
    ]
