# Generated by Django 3.1.4 on 2020-12-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_transactions_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='device_info',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='device',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
