# Generated by Django 3.1.1 on 2020-10-18 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20201002_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Axle Type',
            },
        ),
        migrations.CreateModel(
            name='Ticketsaxle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('groupa', models.CharField(max_length=50)),
                ('groupb', models.CharField(default=None, max_length=50)),
                ('groupc', models.CharField(default=None, max_length=50)),
                ('groupd', models.CharField(default=None, max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('front_photo', models.FileField(default=None, upload_to='documents/tractors/tickets/front')),
                ('side_photo', models.FileField(default=None, upload_to='documents/tractors/tickets/side')),
                ('back_photo', models.FileField(default=None, upload_to='documents/tractors/tickets/back')),
                ('plate_photo', models.FileField(default=None, upload_to='documents/tractors/tickets/plate')),
                ('operation', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=10)),
                ('axle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.axletype')),
                ('commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.commodity')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.customers')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.destination')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.operators')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.origin')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.suppliers')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.vehicle')),
                ('weigh_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.weighstages')),
                ('weighbridge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.weighbridges')),
            ],
            options={
                'verbose_name_plural': ' Tickets Axle Weighing',
            },
        ),
    ]
