# Generated by Django 3.1.1 on 2020-10-30 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_axletype_ticketsaxle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Cooperatives',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imei', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Factories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.cooperatives')),
            ],
            options={
                'verbose_name_plural': 'Factories/Collection Centres',
            },
        ),
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('bank_account', models.CharField(max_length=50)),
                ('bank_account_name', models.CharField(max_length=50)),
                ('acres', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('factory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.factories')),
            ],
            options={
                'verbose_name_plural': 'Farmers',
            },
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Produce',
            },
        ),
        migrations.RenameField(
            model_name='axletype',
            old_name='desc',
            new_name='axles',
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_code', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('total_payout', models.CharField(max_length=50)),
                ('tx_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.devices')),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.farmers')),
                ('produce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.produce')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('tx_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.transactions')),
            ],
            options={
                'verbose_name_plural': 'Payment',
            },
        ),
        migrations.AddField(
            model_name='factories',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.produce'),
        ),
        migrations.AddField(
            model_name='devices',
            name='factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.factories'),
        ),
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('factory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.factories')),
            ],
            options={
                'verbose_name_plural': 'Clerks',
            },
        ),
    ]
