# Generated by Django 3.1.4 on 2021-01-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_auto_20210108_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audits',
            name='action',
            field=models.TextField(),
        ),
    ]
