# Generated by Django 3.1.2 on 2020-11-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_auto_20201110_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerk',
            name='national_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='clerk',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='national_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
