# Generated by Django 3.1.2 on 2020-11-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_auto_20201112_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerk',
            name='phone_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='phone_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
